---
- hosts: app
  remote_user: root

  tasks:
  - name: Update apache state
    yum: name=httpd state=latest
  - name: check httpd for running
      service:
          name: httpd
          state: started
  - name: Copy index.html
      copy:
        src: ~/ansible/index.html
        dest: /usr/share/httpd/noindex/index.html
      become: yes
