---
- hosts: nginx
  tasks:
    - name: Latest nginx
      yum: name=nginx state=latest
      become: yes
    - name: Run nginx
      service:
          name: nginx
          state: started
      become: yes
    - name: Copy nginx conf
      copy:
        src: ~/ansible/nginx.conf
        dest: /etc/nginx/nginx.conf
      become: yes
    - name: Rerun nginx
      service:
        name: nginx
        state: restarted
      become: yes
